baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Canadian Water Levels"

[taxonomies]
province = "provinces"
category = "categories"

[[menu.main]]
name = "Blog"
weight = -120
identifier = "blog"
url = "/posts/"

[[menu.main]]
name = "About"
weight = -110
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Meters"
weight = -115
identifier = "meters"
url = "/meters/"
