baseurl = "http://waterlevels.ca/"
languageCode = "en-us"
title = "Canadian Water Levels"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = ""

[taxonomies]
tag = "tags"
province = "provinces"

[params]
	# General information
	author = "Nick Spacek"
	description = "A site for publishing water levels around Canada"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/nickspacek/canadian-water-levels"

	version = "0.1.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["stylesheets/list.css"]
	custom_js  = []

	[params.palette]
    	primary = "blue"
    	accent  = "light green"


[social]
	twitter = ""
	github  = "nickspacek"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Meters"
	url    = "meter/"
	weight = 10

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 30

[[menu.main]]
	name   = "News"
	url    = "post/"
	weight = 20

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
